name: watchlist
description: "Movies watchlist"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.5.4
  flutter: 3.24.3

dependencies:
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logger: ^2.4.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: '>=8.0.0 <10.0.0'

flutter:
  
  uses-material-design: true
